import importlib
import warnings
from contextlib import contextmanager

from dirty_equals import IsInt
from fastapi.testclient import TestClient
from inline_snapshot import Is, snapshot
from sqlalchemy import StaticPool
from sqlmodel import SQLModel, create_engine
from sqlmodel.main import default_registry
from tryke import expect, test

from ..._shims import import_tutorial


def clear_sqlmodel():
    SQLModel.metadata.clear()
    default_registry.dispose()


@contextmanager
def _client_for(name: str):
    clear_sqlmodel()
    with warnings.catch_warnings(record=True):
        warnings.simplefilter("always")
        mod = import_tutorial("sql_databases", name)
        clear_sqlmodel()
        importlib.reload(mod)
    mod.sqlite_url = "sqlite://"
    mod.engine = create_engine(
        mod.sqlite_url,
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )

    with TestClient(mod.app) as c:
        try:
            yield c
        finally:
            mod.engine.dispose()


@test.cases(
    test.case("tutorial002_py310", name="tutorial002_py310"),
    test.case("tutorial002_an_py310", name="tutorial002_an_py310"),
)
def crud_app(name: str):
    with _client_for(name) as client:
        with warnings.catch_warnings(record=True):
            warnings.simplefilter("always")
            response = client.get("heroes/")
            expect(response.status_code).to_equal(200).fatal()
            expect(response.json()).to_equal([])

            response = client.post(
                "/heroes/",
                json={
                    "id": 9000,
                    "name": "Dead Pond",
                    "age": 30,
                    "secret_name": "Dive Wilson",
                },
            )
            expect(response.status_code).to_equal(200).fatal()
            expect(response.json()).to_equal(
                snapshot({"age": 30, "id": IsInt(), "name": "Dead Pond"})
            )
            # The ID should be generated by the database, not 9000.
            expect(response.json()["id"]).not_.to_equal(9000)

            hero_id = response.json()["id"]
            response = client.get(f"/heroes/{hero_id}")
            expect(response.status_code).to_equal(200).fatal()
            expect(response.json()).to_equal(
                snapshot({"name": "Dead Pond", "age": 30, "id": IsInt()})
            )

            response = client.post(
                "/heroes/",
                json={
                    "name": "Spider-Boy",
                    "age": 18,
                    "secret_name": "Pedro Parqueador",
                },
            )
            expect(response.status_code).to_equal(200).fatal()
            response = client.post(
                "/heroes/", json={"name": "Rusty-Man", "secret_name": "Tommy Sharp"}
            )
            expect(response.status_code).to_equal(200).fatal()

            response = client.get("/heroes/")
            expect(response.status_code).to_equal(200).fatal()
            expect(response.json()).to_equal(
                snapshot(
                    [
                        {"name": "Dead Pond", "age": 30, "id": IsInt()},
                        {"name": "Spider-Boy", "age": 18, "id": IsInt()},
                        {"name": "Rusty-Man", "age": None, "id": IsInt()},
                    ]
                )
            )

            response = client.get("/heroes/?offset=1&limit=1")
            expect(response.status_code).to_equal(200).fatal()
            expect(response.json()).to_equal(
                snapshot([{"name": "Spider-Boy", "age": 18, "id": IsInt()}])
            )

            response = client.patch(
                f"/heroes/{hero_id}", json={"name": "Dog Pond", "age": None}
            )
            expect(response.status_code).to_equal(200).fatal()
            expect(response.json()).to_equal(
                snapshot({"name": "Dog Pond", "age": None, "id": Is(hero_id)})
            )

            response = client.get(f"/heroes/{hero_id}")
            expect(response.status_code).to_equal(200).fatal()
            expect(response.json()).to_equal(
                snapshot({"name": "Dog Pond", "age": None, "id": Is(hero_id)})
            )

            response = client.delete(f"/heroes/{hero_id}")
            expect(response.status_code).to_equal(200).fatal()
            expect(response.json()).to_equal(snapshot({"ok": True}))

            response = client.get(f"/heroes/{hero_id}")
            expect(response.status_code).to_equal(404).fatal()

            response = client.delete(f"/heroes/{hero_id}")
            expect(response.status_code).to_equal(404).fatal()
            expect(response.json()).to_equal(snapshot({"detail": "Hero not found"}))

            response = client.patch(f"/heroes/{hero_id}", json={"name": "Dog Pond"})
            expect(response.status_code).to_equal(404).fatal()
            expect(response.json()).to_equal(snapshot({"detail": "Hero not found"}))


@test.cases(
    test.case("tutorial002_py310", name="tutorial002_py310"),
    test.case("tutorial002_an_py310", name="tutorial002_an_py310"),
)
def openapi_schema(name: str):
    with _client_for(name) as client:
        response = client.get("/openapi.json")
        expect(response.status_code).to_equal(200).fatal()
        expect(response.json()).to_equal(
            snapshot(
                {
                    "openapi": "3.1.0",
                    "info": {"title": "FastAPI", "version": "0.1.0"},
                    "paths": {
                        "/heroes/": {
                            "post": {
                                "summary": "Create Hero",
                                "operationId": "create_hero_heroes__post",
                                "requestBody": {
                                    "required": True,
                                    "content": {
                                        "application/json": {
                                            "schema": {
                                                "$ref": "#/components/schemas/HeroCreate"
                                            }
                                        }
                                    },
                                },
                                "responses": {
                                    "200": {
                                        "description": "Successful Response",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "$ref": "#/components/schemas/HeroPublic"
                                                }
                                            }
                                        },
                                    },
                                    "422": {
                                        "description": "Validation Error",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "$ref": "#/components/schemas/HTTPValidationError"
                                                }
                                            }
                                        },
                                    },
                                },
                            },
                            "get": {
                                "summary": "Read Heroes",
                                "operationId": "read_heroes_heroes__get",
                                "parameters": [
                                    {
                                        "name": "offset",
                                        "in": "query",
                                        "required": False,
                                        "schema": {
                                            "type": "integer",
                                            "default": 0,
                                            "title": "Offset",
                                        },
                                    },
                                    {
                                        "name": "limit",
                                        "in": "query",
                                        "required": False,
                                        "schema": {
                                            "type": "integer",
                                            "maximum": 100,
                                            "default": 100,
                                            "title": "Limit",
                                        },
                                    },
                                ],
                                "responses": {
                                    "200": {
                                        "description": "Successful Response",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "type": "array",
                                                    "items": {
                                                        "$ref": "#/components/schemas/HeroPublic"
                                                    },
                                                    "title": "Response Read Heroes Heroes  Get",
                                                }
                                            }
                                        },
                                    },
                                    "422": {
                                        "description": "Validation Error",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "$ref": "#/components/schemas/HTTPValidationError"
                                                }
                                            }
                                        },
                                    },
                                },
                            },
                        },
                        "/heroes/{hero_id}": {
                            "get": {
                                "summary": "Read Hero",
                                "operationId": "read_hero_heroes__hero_id__get",
                                "parameters": [
                                    {
                                        "name": "hero_id",
                                        "in": "path",
                                        "required": True,
                                        "schema": {
                                            "type": "integer",
                                            "title": "Hero Id",
                                        },
                                    }
                                ],
                                "responses": {
                                    "200": {
                                        "description": "Successful Response",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "$ref": "#/components/schemas/HeroPublic"
                                                }
                                            }
                                        },
                                    },
                                    "422": {
                                        "description": "Validation Error",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "$ref": "#/components/schemas/HTTPValidationError"
                                                }
                                            }
                                        },
                                    },
                                },
                            },
                            "patch": {
                                "summary": "Update Hero",
                                "operationId": "update_hero_heroes__hero_id__patch",
                                "parameters": [
                                    {
                                        "name": "hero_id",
                                        "in": "path",
                                        "required": True,
                                        "schema": {
                                            "type": "integer",
                                            "title": "Hero Id",
                                        },
                                    }
                                ],
                                "requestBody": {
                                    "required": True,
                                    "content": {
                                        "application/json": {
                                            "schema": {
                                                "$ref": "#/components/schemas/HeroUpdate"
                                            }
                                        }
                                    },
                                },
                                "responses": {
                                    "200": {
                                        "description": "Successful Response",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "$ref": "#/components/schemas/HeroPublic"
                                                }
                                            }
                                        },
                                    },
                                    "422": {
                                        "description": "Validation Error",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "$ref": "#/components/schemas/HTTPValidationError"
                                                }
                                            }
                                        },
                                    },
                                },
                            },
                            "delete": {
                                "summary": "Delete Hero",
                                "operationId": "delete_hero_heroes__hero_id__delete",
                                "parameters": [
                                    {
                                        "name": "hero_id",
                                        "in": "path",
                                        "required": True,
                                        "schema": {
                                            "type": "integer",
                                            "title": "Hero Id",
                                        },
                                    }
                                ],
                                "responses": {
                                    "200": {
                                        "description": "Successful Response",
                                        "content": {"application/json": {"schema": {}}},
                                    },
                                    "422": {
                                        "description": "Validation Error",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "$ref": "#/components/schemas/HTTPValidationError"
                                                }
                                            }
                                        },
                                    },
                                },
                            },
                        },
                    },
                    "components": {
                        "schemas": {
                            "HTTPValidationError": {
                                "properties": {
                                    "detail": {
                                        "items": {
                                            "$ref": "#/components/schemas/ValidationError"
                                        },
                                        "type": "array",
                                        "title": "Detail",
                                    }
                                },
                                "type": "object",
                                "title": "HTTPValidationError",
                            },
                            "HeroCreate": {
                                "properties": {
                                    "name": {"type": "string", "title": "Name"},
                                    "age": {
                                        "anyOf": [
                                            {"type": "integer"},
                                            {"type": "null"},
                                        ],
                                        "title": "Age",
                                    },
                                    "secret_name": {
                                        "type": "string",
                                        "title": "Secret Name",
                                    },
                                },
                                "type": "object",
                                "required": ["name", "secret_name"],
                                "title": "HeroCreate",
                            },
                            "HeroPublic": {
                                "properties": {
                                    "name": {"type": "string", "title": "Name"},
                                    "age": {
                                        "anyOf": [
                                            {"type": "integer"},
                                            {"type": "null"},
                                        ],
                                        "title": "Age",
                                    },
                                    "id": {"type": "integer", "title": "Id"},
                                },
                                "type": "object",
                                "required": ["name", "id"],
                                "title": "HeroPublic",
                            },
                            "HeroUpdate": {
                                "properties": {
                                    "name": {
                                        "anyOf": [{"type": "string"}, {"type": "null"}],
                                        "title": "Name",
                                    },
                                    "age": {
                                        "anyOf": [
                                            {"type": "integer"},
                                            {"type": "null"},
                                        ],
                                        "title": "Age",
                                    },
                                    "secret_name": {
                                        "anyOf": [{"type": "string"}, {"type": "null"}],
                                        "title": "Secret Name",
                                    },
                                },
                                "type": "object",
                                "title": "HeroUpdate",
                            },
                            "ValidationError": {
                                "properties": {
                                    "ctx": {"title": "Context", "type": "object"},
                                    "input": {"title": "Input"},
                                    "loc": {
                                        "items": {
                                            "anyOf": [
                                                {"type": "string"},
                                                {"type": "integer"},
                                            ]
                                        },
                                        "type": "array",
                                        "title": "Location",
                                    },
                                    "msg": {"type": "string", "title": "Message"},
                                    "type": {"type": "string", "title": "Error Type"},
                                },
                                "type": "object",
                                "required": ["loc", "msg", "type"],
                                "title": "ValidationError",
                            },
                        }
                    },
                }
            )
        )
